name: CI
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Set up minikube
        uses: medyagh/setup-minikube@master
      - name: test
        run: |
          make install
          go test ./test/kuo_test.go
